apiVersion: v1
data:
  blackbox.yml: |-
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: monitoring